const path = require("node:path");

const POLL_INTERVAL_MS = 5 * 60 * 1000;
const DATA_FILE = path.join(process.cwd(), "data", "data.json");
const DATA_BACKUP_DIR = path.join(process.cwd(), "data", "backups");
const DATA_SCHEMA_VERSION = 4;
const DATA_BACKUP_INTERVAL_MS = Number(process.env.DATA_BACKUP_INTERVAL_MS || (6 * 60 * 60 * 1000));
const DATA_BACKUP_RETENTION = Number(process.env.DATA_BACKUP_RETENTION || 30);
const DEFAULT_PREFIX = "?n";
const MAX_PREFIX_LENGTH = 5;
const DEFAULT_CUSTOM_MESSAGE = "Ada video baru dari {channel}!";
const LEGACY_DEFAULT_CUSTOM_MESSAGE = "Ada video baru dari {channel}! {title} - {link}";
const DEFAULT_CONTENT_FILTER = "all";
const DEFAULT_EMBED_LAYOUT = "compact";
const DEFAULT_PREVIEW_ON_ADD = true;
const DEFAULT_USER_LOG_LEVEL = "warn";
const DEFAULT_DEV_LOG_LEVEL = "warn";
const LOG_LEVELS = {
  INFO: "info",
  WARN: "warn",
  ERROR: "error"
};
const DEFAULT_GUILD_WHITELIST_ENABLED = false;
const DEFAULT_USER_WHITELIST_ENABLED = false;
const DEFAULT_LEAVE_UNAUTHORIZED_GUILDS = false;
const DEFAULT_TITLE_WATCH_MAX_AGE_DAYS = 3;
const MAX_TITLE_WATCH_MAX_AGE_DAYS = 30;
const TITLE_WATCH_SEARCH_LIMIT = 10;
const TITLE_WATCH_HISTORY_LIMIT = 25;
const HEAVY_COMMAND_RATE_LIMIT_MS = 15 * 1000;
const SETTINGS_COMMAND_RATE_LIMIT_MS = 5 * 1000;
const OWNER_COMMAND_RATE_LIMIT_MS = 3 * 1000;
const SENSITIVE_COMMAND_BUCKET_RATE_LIMIT_MS = Number(process.env.SENSITIVE_COMMAND_BUCKET_RATE_LIMIT_MS || 10 * 1000);
const NOTIFICATION_GUARD_WINDOW_MS = 30 * 60 * 1000;
const NOTIFICATION_HISTORY_WINDOW_MS = Number(process.env.NOTIFICATION_HISTORY_WINDOW_MS || 24 * 60 * 60 * 1000);
const RSS_FAILURE_LOG_THRESHOLD = Number(process.env.RSS_FAILURE_LOG_THRESHOLD || 3);
const RSS_FAILURE_LOG_REPEAT_EVERY = Number(process.env.RSS_FAILURE_LOG_REPEAT_EVERY || 6);
const RSS_RECENT_VIDEOS_LIMIT = Number(process.env.RSS_RECENT_VIDEOS_LIMIT || 5);
const LOG_GUARD_WINDOW_MS = 30 * 60 * 1000;
const HTTP_RETRY_ATTEMPTS = Number(process.env.HTTP_RETRY_ATTEMPTS || 3);
const RSS_RETRY_ATTEMPTS = Number(process.env.RSS_RETRY_ATTEMPTS || 3);
const RETRY_BASE_DELAY_MS = Number(process.env.RETRY_BASE_DELAY_MS || 750);
const MAX_TRACKERS_PER_GUILD = Number(process.env.MAX_TRACKERS_PER_GUILD || 100);
const MAX_TITLE_WATCHES_PER_GUILD = Number(process.env.MAX_TITLE_WATCHES_PER_GUILD || 50);
const CANARY_ENABLED = String(process.env.CANARY_ENABLED || "false").toLowerCase() === "true";
const CANARY_INTERVAL_MS = Number(process.env.CANARY_INTERVAL_MS || 30 * 60 * 1000);
const CANARY_FAILURE_THRESHOLD = Number(process.env.CANARY_FAILURE_THRESHOLD || 3);
const EXTERNAL_LOG_WEBHOOK_URL = String(process.env.EXTERNAL_LOG_WEBHOOK_URL || "").trim() || null;
const CONTENT_FILTERS = {
  ALL: "all",
  VIDEO: "video",
  LONG: "long",
  SHORTS: "shorts",
  LIVE: "live",
  LIVE_UPCOMING: "live_upcoming",
  LIVE_NOW: "live_now",
  LIVE_REPLAY: "live_replay",
  PREMIERE: "premiere",
  PREMIERE_UPCOMING: "premiere_upcoming",
  PREMIERE_PUBLISHED: "premiere_published"
};
const EMBED_LAYOUTS = {
  COMPACT: "compact",
  RICH: "rich"
};
const YOUTUBE_BASE_URL = "https://www.youtube.com";
const YOUTUBE_RSS_URL = "https://www.youtube.com/feeds/videos.xml?channel_id=";

const DEFAULT_HEADERS = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/123.0.0.0 Safari/537.36",
  "Accept-Language": "en-US,en;q=0.9,id;q=0.8"
};

module.exports = {
  DATA_BACKUP_DIR,
  DATA_BACKUP_INTERVAL_MS,
  DATA_BACKUP_RETENTION,
  DATA_FILE,
  DATA_SCHEMA_VERSION,
  CONTENT_FILTERS,
  DEFAULT_CONTENT_FILTER,
  DEFAULT_CUSTOM_MESSAGE,
  DEFAULT_EMBED_LAYOUT,
  DEFAULT_GUILD_WHITELIST_ENABLED,
  DEFAULT_LEAVE_UNAUTHORIZED_GUILDS,
  DEFAULT_PREVIEW_ON_ADD,
  DEFAULT_USER_LOG_LEVEL,
  DEFAULT_DEV_LOG_LEVEL,
  DEFAULT_TITLE_WATCH_MAX_AGE_DAYS,
  DEFAULT_USER_WHITELIST_ENABLED,
  LEGACY_DEFAULT_CUSTOM_MESSAGE,
  LOG_LEVELS,
  DEFAULT_PREFIX,
  DEFAULT_HEADERS,
  EMBED_LAYOUTS,
  HEAVY_COMMAND_RATE_LIMIT_MS,
  LOG_GUARD_WINDOW_MS,
  MAX_PREFIX_LENGTH,
  MAX_TITLE_WATCH_MAX_AGE_DAYS,
  NOTIFICATION_GUARD_WINDOW_MS,
  NOTIFICATION_HISTORY_WINDOW_MS,
  RSS_FAILURE_LOG_THRESHOLD,
  RSS_FAILURE_LOG_REPEAT_EVERY,
  RSS_RECENT_VIDEOS_LIMIT,
  OWNER_COMMAND_RATE_LIMIT_MS,
  POLL_INTERVAL_MS,
  SENSITIVE_COMMAND_BUCKET_RATE_LIMIT_MS,
  HTTP_RETRY_ATTEMPTS,
  RSS_RETRY_ATTEMPTS,
  RETRY_BASE_DELAY_MS,
  MAX_TRACKERS_PER_GUILD,
  MAX_TITLE_WATCHES_PER_GUILD,
  CANARY_ENABLED,
  CANARY_INTERVAL_MS,
  CANARY_FAILURE_THRESHOLD,
  EXTERNAL_LOG_WEBHOOK_URL,
  SETTINGS_COMMAND_RATE_LIMIT_MS,
  TITLE_WATCH_HISTORY_LIMIT,
  TITLE_WATCH_SEARCH_LIMIT,
  YOUTUBE_BASE_URL,
  YOUTUBE_RSS_URL
};
